version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 
- package-ecosystem: github-actions
  directory: "/"
  schedule:
     interval: daily
  open-pull-requests-limit: 10   
  
  
