apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
   name: "applications.nais.io"
spec:
   group: "nais.io"
   version: "v1alpha1"
   scope: "Namespaced"
   names:
      plural: "applications"
      singular: "application"
      kind: "Application"
      shortNames:
      - app
   validation:
      openAPIV3Schema:
         properties:
            spec:
               properties:
                  image: repo.adeo.no:5443/fp-uttak-service
                  team: bris
                  replicas:
                     properties:
                        min: 2
                        max: 2
                        cpuThresholdPercentage: 50
                  port: 8080
                  healthcheck:
                     properties:
                        liveness:
                           properties:
                              path: /isAlive
                              initialDelay: 60
                        readiness:
                           properties:
                              path: /isReady
                              initialDelay: 60
                  prometheus:
                     properties:
                        enabled: false
                  istio: false
                  resources:
                     properties:
                        limits:
                           properties:
                              cpu: 1500m
                              memory: 3072Mi
                        requests:
                           properties:
                              cpu: 250m
                              memory: 1536Mi
                  webproxy: false
                  secrets: false

