apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-uttak-service
  namespace: {{namespace}}
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /isAlive
      initialDelay: 60
  readiness:
      path: /isReady
      initialDelay: 60  
  prometheus:
      enabled: false
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  webproxy: true
