name: Bygg branch eller PR

on: 
  pull_request:
  push:
    branches-ignore:   
      - master   

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle.kts') }}
            restore-keys: |
              ${{ runner.os }}-gradle-cache-
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-wrapper-
        - uses: actions/setup-java@v1
          with:
            java-version: 1.11

        - name: test and build
          run: ./gradlew -b build.gradle.kts fatJar 
