name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  NAMESPACE: teamforeldrepenger
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fp-uttak-service

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:

      - name: Set variabler for image og cluster
        run: |
           echo "TAG=$(echo ${{ github.event.client_payload.github.payload.issue.title }} | awk '{print $NF}' | awk -F- '{print $NF}')" >> $GITHUB_ENV
           echo "IMAGE=$IMAGE_BASE:$(echo ${{ github.event.client_payload.github.payload.issue.title }} | awk '{print $NF}')" >> $GITHUB_ENV
           echo "CLUSTER=${{ github.event.client_payload.slash_command.arg1 }}" >> $GITHUB_ENV


      - name: Sjekk ut kode
        uses: actions/checkout@v1
        with:
          ref: ${{ env.TAG }}

      - name: Promoter til cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: ${{ env.CLUSTER }}-${{ env.NAMESPACE }}.json

      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            >promote ${{ github.event.client_payload.slash_command.args }} feilet
          reaction-type: -1

      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    body: '>promote ${{ github.event.client_payload.slash_command.args }} var OK'})
            github.issues.addLabels({...issue, labels: ['${{ env.CLUSTER }}:${{ env.NAMESPACE }}']})


